// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package slack

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SlackClient is the client API for Slack service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SlackClient interface {
	Announce(ctx context.Context, in *AnnounceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type slackClient struct {
	cc grpc.ClientConnInterface
}

func NewSlackClient(cc grpc.ClientConnInterface) SlackClient {
	return &slackClient{cc}
}

func (c *slackClient) Announce(ctx context.Context, in *AnnounceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/slack.Slack/Announce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SlackServer is the server API for Slack service.
// All implementations must embed UnimplementedSlackServer
// for forward compatibility
type SlackServer interface {
	Announce(context.Context, *AnnounceRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSlackServer()
}

// UnimplementedSlackServer must be embedded to have forward compatible implementations.
type UnimplementedSlackServer struct {
}

func (UnimplementedSlackServer) Announce(context.Context, *AnnounceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Announce not implemented")
}
func (UnimplementedSlackServer) mustEmbedUnimplementedSlackServer() {}

// UnsafeSlackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SlackServer will
// result in compilation errors.
type UnsafeSlackServer interface {
	mustEmbedUnimplementedSlackServer()
}

func RegisterSlackServer(s grpc.ServiceRegistrar, srv SlackServer) {
	s.RegisterService(&Slack_ServiceDesc, srv)
}

func _Slack_Announce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlackServer).Announce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slack.Slack/Announce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlackServer).Announce(ctx, req.(*AnnounceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Slack_ServiceDesc is the grpc.ServiceDesc for Slack service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Slack_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slack.Slack",
	HandlerType: (*SlackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Announce",
			Handler:    _Slack_Announce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testthedog/slack/slack.proto",
}
